name: Compile mos-notify

on:
  # Allow to trigger action manually
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.8'

    - name: Execute GO tidy
      run: go mod tidy

    - name: Build mos-notify and create .deb package for amd64
      run: |
        BUILDDIR=${{ github.workspace }}
        PACKAGEDIR=$BUILDDIR/mos-notify_package
        mkdir -p $PACKAGEDIR/DEBIAN $PACKAGEDIR/usr/bin $PACKAGEDIR/usr/share/doc/mos-notify $PACKAGEDIR/var/mos/notify

        go build -ldflags="-s -w" -o mos-notify

        mv $BUILDDIR/mos-notify $PACKAGEDIR/usr/bin/mos-notify

        # Add LICENSE from repo:
        cp "${{ github.workspace }}/LICENSE" "$PACKAGEDIR/usr/share/doc/mos-notify/LICENSE"
        echo -e "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/\nUpstream-Name: MOS\nSource: https://github.com/${{ github.repository_owner }}/mos-notify\n\nFiles: *\nCopyright: 2025 Christoph Hummer\nLicense: GPL-2.0" >> $PACKAGEDIR/usr/share/doc/mos-notify/copyright

        echo "[]" > $PACKAGEDIR/var/mos/notify/notifications.json

        cat > $PACKAGEDIR/DEBIAN/control << EOF
        Package: mos-notify
        Version: ${{ github.event.inputs.version }}-mos
        Architecture: amd64
        Maintainer: admin@minenet.at
        Description: mos-notify for MOS
        EOF

        cd $BUILDDIR
        chmod -R 755 $PACKAGEDIR
        dpkg-deb --build mos-notify_package mos-notify_${{ github.event.inputs.version }}_amd64.deb
        md5sum $BUILDDIR/mos-notify_${{ github.event.inputs.version }}_amd64.deb | awk '{print $1}' > $BUILDDIR/mos-notify_${{ github.event.inputs.version }}_amd64.deb.md5

    - name: Build mos-notify and create .deb package for arm64
      run: |
        BUILDDIR=${{ github.workspace }}
        PACKAGEDIR=$BUILDDIR/mos-notify_package
        rm -rf $BUILDDIR/mos-notify $PACKAGEDIR
        mkdir -p $PACKAGEDIR/DEBIAN $PACKAGEDIR/usr/bin $PACKAGEDIR/usr/share/doc/mos-notify $PACKAGEDIR/var/mos/notify

        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o mos-notify

        mv $BUILDDIR/mos-notify $PACKAGEDIR/usr/bin/mos-notify

        # Add LICENSE from repo:
        cp "${{ github.workspace }}/LICENSE" "$PACKAGEDIR/usr/share/doc/mos-notify/LICENSE"
        echo -e "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/\nUpstream-Name: MOS\nSource: https://github.com/${{ github.repository_owner }}/mos-notify\n\nFiles: *\nCopyright: 2025 Christoph Hummer\nLicense: GPL-2.0" >> $PACKAGEDIR/usr/share/doc/mos-notify/copyright

        echo "[]" > $PACKAGEDIR/var/mos/notify/notifications.json

        cat > $PACKAGEDIR/DEBIAN/control << EOF
        Package: mos-notify
        Version: ${{ github.event.inputs.version }}-mos
        Architecture: arm64
        Maintainer: admin@minenet.at
        Description: mos-notify for MOS
        EOF

        cd $BUILDDIR
        chmod -R 755 $PACKAGEDIR
        dpkg-deb --build mos-notify_package mos-notify_${{ github.event.inputs.version }}_arm64.deb
        md5sum $BUILDDIR/mos-notify_${{ github.event.inputs.version }}_arm64.deb | awk '{print $1}' > $BUILDDIR/mos-notify_${{ github.event.inputs.version }}_arm64.deb.md5
    

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: "mos-notify v${{ github.event.inputs.version }}"
        body: Docker mos-notify for MOS
        files: |
          ${{ github.workspace }}/mos-notify*
        overwrite_files: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup
      if: always()
      run: rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.*
